version: '3.3'

volumes:
  postgres_data:
  media_volumes:
  static_volumes:

services:
  db:
    image: postgres:12.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  web:
    image: ndvg/yamdb_final:latest
    restart: always
    depends_on:
      - db
    volumes:
      - static_volumes:/code/static
      - media_volumes:/code/media
    env_file:
      - ./.env

  web_nginx:
    image: nginx:1.19.6
    restart: always
    volumes:
      - static_volumes:/code/static
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - media_volumes:/code/media
    ports:
      - "80:80"
    depends_on:
      - web

